In [ ]:
import numpy as np
import numpy.linalg as la # import the necessary modules

1.3 & 1.4 - matrix sums and products

In [39]:
# define the matrices
matrix_B = np.array([[3,0],[-1,5]])
matrix_A = np.array([[1, -3], [4, 2]])
matrix_C = np.array([[5],[9]])
matrix_D = np.array([[1,1,3],[4,-2,3]])
matrix_E = np.array([[1, 2],[0,6],[-2,3]])
matrix_G = np.array([[4, 2, 3],[-2, 6, 0],[0, 7, 1]])
matrix_H = np.array([[1, 0, 1],[5, 2, -2],[2, -3, 4]])

sum_e = 3*matrix_B - matrix_A
print(sum_e, "\n\n")
sum_T = matrix_A.T + matrix_B.T
print(sum_T, "\n\n")
sum_T2 = (matrix_A + matrix_B).T
print(f"sum of the transposes is equal to the transpose of the sum", sum_T2, "\n\n")

product_AC = np.matmul(matrix_A,matrix_C)
print(product_AC, "\n\n")
product_INcorrect = matrix_A*matrix_C
print(f"incorrect product calculation with asterisk", product_INcorrect, "\n")

try:
    product_CA = np.matmul(matrix_C, matrix_A)
    print(product_CA)
except ValueError:
    print("Skipping matrix_C @ matrix_A — incompatible dimensions")


[[ 8  3]
 [-7 13]] 


[[ 4  3]
 [-3  7]] 


sum of the transposes is equal to the transpose of the sum [[ 4  3]
 [-3  7]] 


[[-22]
 [ 38]] 


incorrect product calculation with asterisk [[  5 -15]
 [ 36  18]] 

Skipping matrix_C @ matrix_A — incompatible dimensions


In [38]:
product_CTC = np.matmul(matrix_C.T,matrix_C)
print(product_CTC, "\n\n")
product_CCT = np.matmul(matrix_C,matrix_C.T)
print(product_CCT, "\n\n")
product_DE = np.matmul(matrix_D,matrix_E)
print(product_DE, "\n\n")
product_GH = np.matmul(matrix_G,matrix_H)
print(product_GH)

[[106]] 


[[25 45]
 [45 81]] 


[[-5 17]
 [-2  5]] 


[[ 20  -5  12]
 [ 28  12 -14]
 [ 37  11 -10]]


1.5 Calculate the determinants

In [ ]:
detA = la.det(matrix_A)

# detB = la.det(matrix_B)
detG = la.det(matrix_G)
detH = la.det(matrix_H)
print(detA, "\n", detB, "\n", detG, "\n", detH)

14.000000000000004 
 15.0 
 -13.999999999999996 
 -17.0


1.6.A - Calculate the inverse of matrix A

In [40]:
n = matrix_A.shape[0]
minors = np.zeros((n,n))
cofactors = np.zeros((n,n))
for i in range(n):                  # 0-based indices: 0..n-1
    for j in range(n):
        A_sub = np.delete(np.delete(matrix_A, i, axis=0), j, axis=1)
        minor = la.det(A_sub)
        cofactor = ((-1)**(i + j)) * minor
        minors[i, j] = minor
        cofactors[i, j] = cofactor
        print(f"i={i}, j={j} minor: {minor}, cofactor: {cofactor}\n")
# The inverse via cofactors:
if abs(detA) > 0:
    adj = cofactors.T
    A_inv_from_adj = adj / detA
print("Adjugate of A:\n", adj)
print("Inverse from adjugate:\n", A_inv_from_adj)

i=0, j=0 minor: 2.0, cofactor: 2.0

i=0, j=1 minor: 4.0, cofactor: -4.0

i=1, j=0 minor: -3.0000000000000004, cofactor: 3.0000000000000004

i=1, j=1 minor: 1.0, cofactor: 1.0

Adjugate of A:
 [[ 2.  3.]
 [-4.  1.]]
Inverse from adjugate:
 [[ 0.14285714  0.21428571]
 [-0.28571429  0.07142857]]


In [42]:
# or 
inverse_A = la.inv(matrix_A)
print("Inverse from linalg.inv:\n", inverse_A)

Inverse from linalg.inv:
 [[ 0.14285714  0.21428571]
 [-0.28571429  0.07142857]]


1.6.G - Calculate the inverse of matrix G

In [41]:
n = matrix_G.shape[0]
minors = np.zeros((n,n))
cofactors = np.zeros((n,n))
for i in range(n):                  # 0-based indices: 0..n-1
    for j in range(n):
        G_sub = np.delete(np.delete(matrix_G, i, axis=0), j, axis=1)
        minor = la.det(G_sub)
        cofactor = ((-1)**(i + j)) * minor
        minors[i, j] = minor
        cofactors[i, j] = cofactor
        print(f"i={i}, j={j} minor: {minor}, cofactor: {cofactor}\n")
# The inverse via cofactors:
if abs(detG) > 0:
    adj = cofactors.T
    G_inv_from_adj = adj / detG
print("Adjugate of G:\n", adj)
print("Inverse from adjugate:\n", G_inv_from_adj)

i=0, j=0 minor: 6.0, cofactor: 6.0

i=0, j=1 minor: -2.0, cofactor: 2.0

i=0, j=2 minor: -13.999999999999996, cofactor: -13.999999999999996

i=1, j=0 minor: -18.999999999999996, cofactor: 18.999999999999996

i=1, j=1 minor: 4.0, cofactor: 4.0

i=1, j=2 minor: 27.999999999999996, cofactor: -27.999999999999996

i=2, j=0 minor: -17.999999999999996, cofactor: -17.999999999999996

i=2, j=1 minor: 6.0, cofactor: -6.0

i=2, j=2 minor: 27.999999999999996, cofactor: 27.999999999999996

Adjugate of G:
 [[  6.  19. -18.]
 [  2.   4.  -6.]
 [-14. -28.  28.]]
Inverse from adjugate:
 [[-0.42857143 -1.35714286  1.28571429]
 [-0.14285714 -0.28571429  0.42857143]
 [ 1.          2.         -2.        ]]


In [43]:
# or 
inverse_G = la.inv(matrix_G)
print("Inverse from linalg.inv:\n", inverse_G)

Inverse from linalg.inv:
 [[-0.42857143 -1.35714286  1.28571429]
 [-0.14285714 -0.28571429  0.42857143]
 [ 1.          2.         -2.        ]]
